config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }, skip: [:sessions] 
    as :user do
      get 'login' => 'devise/sessions#new', :as => :new_user_session
      post 'login' => 'devise/sessions#create', :as => :user_session
      delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    end

  devise_scope :user do
    get "/signup" => "users/registrations#new"
    get "/profile" => 'users/registrations#edit'
  end

  resources :tags

  scope "/tasks" do
    get'/new', to: 'tasks#quick_new_task', as: "quick_new_task"
    post'/', to: 'tasks#create', as: "post_quick_new_task"
    get'/all-active-tasks', to: 'tasks#all_active_tasks', as: "all_active_tasks"
    get'/all-complete-tasks', to: 'tasks#all_complete_tasks', as: "all_complete_tasks"
    get'/all-overdue-tasks', to: 'tasks#all_overdue_tasks', as: "all_overdue_tasks"
  end

  resources :projects do
    get :overdue, on: :collection
    get :complete, on: :collection

    post '/delete_collaborator', to: 'projects#delete_collaborator'

    resources :comments, :notes, shallow: true

    resources :tasks, shallow: true do 
      get :complete, on: :collection, to: "tasks#complete"
      get :overdue, on: :collection, to: "tasks#overdue"
    end
  end

  patch '/edit_user_project_permission', to: 'user_projects#edit_user_project_permission'

  namespace :admin do 
    get 'dashboard' => 'dashboard#index', :as => :dashboard
    get 'tags' => 'dashboard#tags', :as => :tags
    get 'users' => 'dashboard#users', :as => :users
    get 'users/:id' => 'dashboard#user_edit', :as => :user_edit
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include DateTimeConverter
  include IndexCheck

  belongs_to :user
  belongs_to :task

  validates :content, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout "comments_layout", only: [:index]
  layout "tasks_layout"
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :set_task, only: [:edit, :update, :destroy]
  before_action :set_project
  
  ## STANDARD RESTFUL ROUTES

  def index
    if @project.owner == @user || @user.admin? || @project.collaborators.include?(@user)
      @comments = @project.comments.reverse
    else
      flash[:alert] = "You are not authorized to perform that action."
      redirect_to root_path
    end
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      @task = @comment.task
      redirect_to task_path(@task)
    else
      @comments = @task.comments
      render 'tasks/show'
    end
  end

  def edit
    authorize @comment
  end

  def update
    authorize @comment
    @comment.update(comment_params)
    redirect_to task_path(@task)
  end

  def destroy
    authorize @comment
    @comment.destroy
    redirect_to task_path(@task)
  end

  ## PRIVATE METHODS

  private
  def set_comment
    @comment = Comment.find_by(id: params[:id])
  end

  def set_task
    @task = set_comment.task
  end

  def set_project
    if params[:id]
       @project = Project.find_by(id: params[:id])
    else
      @project = Project.find_by(id: params[:project_id])
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :task_id, :user_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="<%= col %>" id="<%= comment.id%>">
  <p> Posted: <%= comment.friendly_created_at %> by <%= comment.user.name %></p>
  <p>On <%= link_to comment.task.name, task_path(comment.task) %> in <%= link_to comment.task.project.name, project_path(comment.task.project) %></p>
  <p> <%= comment.content %></p>
  <div class="inline-button">
    <%= link_to "Edit", edit_comment_path(comment), class: "btn btn-sm btn-primary" %> 
  </div>
  <div class="inline-button">    
    <%= button_to "Delete", comment_path(comment), method: :delete, class: "btn btn-sm btn-danger" %>
  </div>
  <div class="line-light"></div>
</div>
<% if comment.index_check(index) %>
  <div class="clearfix"></div>
<% end %>

app/views/comments/_edit_form.html.erb
<%= form_for(comment) do |f| %>
  <div class="form-group">  
    <%= f.text_area :content, class: "comment-text-field form-control", rows: "3" %>
  </div>  
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.hidden_field :task_id, value: @task.id %>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/_new_form.html.erb
<%= form_for(comment, url: project_comments_path(@project)) do |f| %>
  <div class="form-group">  
    <%= f.text_area :content, class: "comment-text-field form-control", rows: "3" %>
  </div>  
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.hidden_field :task_id, value: @task.id %>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h3>Edit Comment</h3>
<div class="line-dark"></div>
<%= render partial: "messages/errors", locals: {resource: @comment} %>
<%= render partial: "comments/edit_form", locals: {comment: @comment} %>

app/views/comments/index.html.erb
<div class="default-block">
  <h2>All Project Comments</h2>
  <div class="line-dark"></div>
  <div class="row">
    <% @comments.each_with_index do |comment, index| %>
      <%= render partial: "comments/comment", locals: {comment: comment, index: index, col: "col-md-4"} %>
    <%end %>
  </div>
</div>