config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }, skip: [:sessions] 
    as :user do
      get 'login' => 'devise/sessions#new', :as => :new_user_session
      post 'login' => 'devise/sessions#create', :as => :user_session
      delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    end

  devise_scope :user do
    get "/signup" => "users/registrations#new"
    get "/profile" => 'users/registrations#edit'
  end

  resources :tags

  scope "/tasks" do
    get'/new', to: 'tasks#quick_new_task', as: "quick_new_task"
    post'/', to: 'tasks#create', as: "post_quick_new_task"
    get'/all-active-tasks', to: 'tasks#all_active_tasks', as: "all_active_tasks"
    get'/all-complete-tasks', to: 'tasks#all_complete_tasks', as: "all_complete_tasks"
    get'/all-overdue-tasks', to: 'tasks#all_overdue_tasks', as: "all_overdue_tasks"
  end

  resources :projects do
    get :overdue, on: :collection
    get :complete, on: :collection

    post '/delete_collaborator', to: 'projects#delete_collaborator'

    resources :comments, :notes, shallow: true

    resources :tasks, shallow: true do 
      get :complete, on: :collection, to: "tasks#complete"
      get :overdue, on: :collection, to: "tasks#overdue"
    end
  end

  patch '/edit_user_project_permission', to: 'user_projects#edit_user_project_permission'

  namespace :admin do 
    get 'dashboard' => 'dashboard#index', :as => :dashboard
    get 'tags' => 'dashboard#tags', :as => :tags
    get 'users' => 'dashboard#users', :as => :users
    get 'users/:id' => 'dashboard#user_edit', :as => :user_edit
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  include DateTimeConverter
  include IndexCheck

  belongs_to :project
  has_many :comments
  has_many :task_tags
  has_many :tags, through: :task_tags

  has_many :user_tasks, foreign_key: "assigned_task_id"
  has_many :assigned_users, through: :user_tasks
  belongs_to :owner, class_name: "User"

  enum status: [:active, :complete]

  validates :name, :description, :due_date, :status, :project_id, presence: true

  scope :complete, -> { where(status: 1) }
  scope :active, -> { where(status: 0)}
  scope :overdue, -> { where("due_date < ? AND status = ?", Date.today, 0)}

  #Custom writer and readers for Task for creating nested attributes

  def tag_names=(tags)
    tag_array = tags.split(",").map{|tag| tag.strip}
    tag_array.each do |tag|
      new_tag = Tag.find_or_create_by(name: tag)
      if self.tags.include?(new_tag)
        next
      end
      self.tags << new_tag
      self.owner.tags << new_tag
    end
  end

  def tag_names
    tags = self.tags.collect {|tag| tag.name}
    tags.join(", ")
  end

  def overdue?
    self.due_date < Date.today ? true : false
  end

end 

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout "tasks_layout"
  before_action :set_task
  before_action :set_project
  before_action :project_task_statuses_count, only: [:index, :complete, :overdue]
  before_action :all_task_statuses_count, only: [:all_active_tasks, :all_complete_tasks, :all_overdue_tasks]

  ## STANDARD RESTFUL ACTIONS

  def index
    @task = Task.new(project_id: @project.id)
    authorize @task
    @tasks = @project.active_tasks
  end

  def new
    @task = Task.new(project_id: @project.id)
    authorize @task
    @task_users = task_users
  end

  def create
    @task = Task.new(task_params)
    authorize @task
    if @task.save
      redirect_to task_path(@task)
    else
      @task_users = task_users
      render :new
    end
  end

  def show
    @project = @task.project
    @comment = Comment.new
    @comments = @task.comments.reverse
    @assigned_users = @task.assigned_users
    @tags = @task.tags
  end

  def edit
    authorize @task
    @project = @task.project
    @task_users = task_users
  end

  def update
    authorize @task
    @task.update(task_params)
    if task_params[:tag_names]
      @task.update(tag_names: task_params[:tag_names])
    end
    redirect_to task_path(@task)
  end

  def destroy
    authorize @task
    @task.destroy
    redirect_to project_tasks_path(@project)
  end

  ## ADDITIONAL ACTIONS

  # PROJECT TASKS 
  def complete
    @tasks = @project.complete_tasks
  end

  def overdue
    @tasks = @project.overdue_tasks
  end

  # ALL USER RELATED TASKS
  def all_active_tasks
    @tasks = (@user.tasks.active + @user.assigned_tasks.active).uniq
    @tasks.flatten!
  end

  def all_complete_tasks
    @tasks = (@user.tasks.complete + @user.assigned_tasks.complete).uniq
    @tasks.flatten!
  end

  def all_overdue_tasks
    @tasks = (@user.tasks.overdue + @user.assigned_tasks.overdue).uniq
    @tasks.flatten!
  end

  def quick_new_task
   @task = Task.new
   @projects = @user.active_projects + @user.collaboration_projects.active
  end

  ## PRIVATE METHODS

  private
  def set_user
    @user = current_user
  end

  def set_task
    @task = Task.find_by(id: params[:id])
  end

  def set_project
    @project = Project.find_by(id: params[:project_id])
  end

  def project_task_statuses_count
    @overdue = @project.overdue_tasks.count
    @active = @project.active_tasks.count
    @complete = @project.complete_tasks.count
  end

  def all_task_statuses_count
    @overdue = (current_user.overdue_tasks + current_user.overdue_assigned_tasks).uniq.count
    @active = (current_user.active_tasks + current_user.active_assigned_tasks).uniq.count
    @complete= (current_user.complete_tasks + current_user.complete_tasks).uniq.count
  end

  def task_params
    params.require(:task).permit(:name, :description, :project_id, :owner_id, :due_date, :status, :tag_names, assigned_user_ids: [], tag_ids: [])
  end

  def task_users
    task_users = []
    task_users << @task.project.collaborators
    task_users << @user
    task_users.flatten
  end
end

app/helpers/tasks_helper.rb
module TasksHelper

  
end

app/views/tasks/_all_task_options.erb
<div class="default-block">
  <div class="inline-button">
    <%= link_to "Add a New Task", quick_new_task_path, class: "btn btn-default td-button" %>
  </div>
   <div class="inline-button">
    <%= link_to "Active Tasks ( #{active} )", all_active_tasks_path, class: "btn btn-warning" %> 
  </div>
  <div class="inline-button">
    <%= link_to "Complete Tasks ( #{complete} )", all_complete_tasks_path, class: "btn btn-success" %>
  </div>
  <div class="inline-button">
    <%= link_to "Overdue Tasks ( #{overdue} )", all_overdue_tasks_path, class: "btn btn-danger" %>
  </div>
</div>

app/views/tasks/_project_task_options.html.erb
<div class="default-block">
  <div class="inline-button">
    <%= link_to "Back to Project", project_path(@project), class: "btn btn-default td-button" %>
  </div>
  <div class="inline-button">
    <%= link_to "New Task", new_project_task_path(@project), class: "btn btn-default td-button" %>
  </div>
  <div class="inline-button">
    <%= link_to "Active tasks ( #{active} )", project_tasks_path(@project), class: "btn btn-warning" %> 
  </div>
  <div class="inline-button">
    <%= link_to "Complete tasks ( #{complete} )", complete_project_tasks_path(@project), class: "btn btn-success" %>
  </div>
  <div class="inline-button">
    <%= link_to "Overdue tasks ( #{overdue} )", overdue_project_tasks_path(@project), class: "btn btn-danger" %>
  </div>
</div>

app/views/tasks/_task.html.erb
<div class="col-md-4">
  <h3> <%= link_to task.name, task_path(task) %> </h3>
  <span class="overdue"> <%= "Overdue" if task.overdue? && !task.complete? %></span>
  <span class="complete"> <%= "Complete" if task.complete? %></span>
  <% if task.assigned_users.include?(current_user) %>
    <p class="collaborator-text"> Assigned to you </p>
  <% end %>
  <p> <%= task.description %> </p>
  <p> Created: <%= task.friendly_created_at %> </p>
  <p> Owner: <%= task.owner.name %> </p>
  <p> Due: <%= task.due_date %>  </p>
  <p> Assigned to: <% task.assigned_users.each do |user| %>
        <%= user.name %>,
          <% end %>
    </p>
  <p> Status: <%= task.status.capitalize %> </p>
  <p> <%= link_to "#{task.comments.count} Comments", task_path(task) %> </p>
  <p> Belongs to: <%= link_to task.project.name, project_path(task.project) %> </p>
  <div class="inline-button">
    <%= link_to "View task", task_path(task), class: "btn btn-default" %>
  </div>
  <div class="inline-button">
    <%= link_to "Edit task", edit_task_path(task), class: "btn btn-default" %>
  </div>
  <div class="inline-button">
    <%= render partial: "task_complete_form", locals: {task: task} unless task.status == "complete" %>
  </div>
 <div class="line-light"> </div>
</div>
<% if task.index_check(index) %>
  <div class="clearfix"></div>
<% end %>

app/views/tasks/_task_complete_form.html.erb
<%= form_for(task)do |f| %>
  <%= f.hidden_field :owner_id, value: @user.id %>
  <%= f.hidden_field :status, value: "complete" %>
  <%= f.submit "Mark Complete", class: "btn btn-sm btn-success"%>
<% end %>

app/views/tasks/all_active_tasks.html.erb
<%= render partial: "all_task_options", locals:{overdue: @overdue, active: @active, complete: @complete} %>

<div class="task-block">
  <h2>All Active Tasks</h2>
  <div class="line-dark"></div>
  <% if @tasks.empty? %>
    <h4>It looks like you don't have any tasks. Why not create new one?</h4>
  <% else %>
    <div class="row">
      <% @tasks.each_with_index do |task, index| %>
        <%= render partial: "task", locals: {task: task, index: index } %>
      <%end %>
    </div>
  <% end %>
</div>

app/views/tasks/all_complete_tasks.erb
<%= render partial: "all_task_options", locals:{overdue: @overdue, active: @active, complete: @complete} %>

<div class="task-block">
  <h2>All Complete Tasks</h2>
  <div class="line-dark"></div>
  <% if @tasks.empty? %>
    <h4>It looks like you don't have any complete tasks yet.</h4>
  <% else %>
    <div class="row">
      <% @tasks.each_with_index do |task, index| %>
        <%= render partial: "task", locals: {task: task, index: index } %>
      <%end %>
    </div>
  <% end %>
</div>

app/views/tasks/all_overdue_tasks.html.erb
<%= render partial: "all_task_options", locals:{overdue: @overdue, active: @active, complete: @complete} %>

<div class="task-block">
  <h2>All Overdue Tasks</h2>
  <div class="line-dark"></div>
  <% if @tasks.empty? %>
    <h4>It looks like you don't have overdue tasks. Good job!</h4>
  <% else %>
    <div class="row">
      <% @tasks.each_with_index do |task, index| %>
        <%= render partial: "task", locals: {task: task, index: index } %>
      <%end %>
    </div>
  <% end %>
</div>

app/views/tasks/complete.html.erb
<%= render partial: "project_task_options", locals:{overdue: @overdue, active: @active, complete: @complete} %>

<div class="task-block">
  <h2>Completed Tasks</h2>
  <div class="line-dark"></div>
  <% if @tasks.empty? %>
    <h4>It looks like you haven't completed any tasks yet. </h4>
  <% else %>
    <div class="row">
      <% @tasks.each_with_index do |task, index| %>
        <%= render partial: "task", locals: {task: task, index: index } %>
      <%end %>
    </div>
  <% end %> <!-- if/else end -->
</div> <!-- block end -->

app/views/tasks/edit.html.erb
<div class="default-block">
  <%= render partial: "messages/errors", locals: {resource: @task} %>
  <h1>Edit Task</h1> 
  <div class="line-dark"></div>
  <%= form_for @task do |f| %>
    <div class="form-group">
      <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
        <%= f.text_field :description, class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :due_date %>
        <%= f.date_select(:due_date, :order => [:month, :day, :year]) %>
    </div>
    <div class="form-group">
      <%= f.label :assigned_users, value: "Assign Users", class: "label-block" %>
        <%= f.collection_check_boxes(:assigned_user_ids, @task_users, :id, :name, html: {class: "form-control"})%>
    </div>
    <div class="form-group">
      <%= f.label :status, class: "label-block" %>
      <%= f.select :status, Task.statuses.collect {|k,v| [k.capitalize, k]}, selected: @task.status %>
    </div>
    <div class="form-group">
      <% if !@task.tags.empty? %>
      <%= f.label :tags, value: "Manage Tags", class: "label-block" %>
        <%= f.collection_check_boxes(:tag_ids, @task.tags, :id, :name, html: {class: "form-control"})%>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :tag_names, "Add tags" %>
        <%= f.text_field :tag_names, value: "", class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.hidden_field :owner_id, value: @user.id %>
      <%= f.hidden_field :project_id, value: @task.project.id %>
      <%= f.submit class: "btn btn-primary"%>
    </div>
  <% end %>
  <%= button_to "Delete Task", task_path(@task), method: :delete, class: "btn btn-danger" %>
</div>

app/views/tasks/index.html.erb
<%= render partial: "project_task_options", locals:{overdue: @overdue, active: @active, complete: @complete} %>

<div class="default-block">
  <h2>Your Tasks</h2>
  <div class="line-dark"></div>
  <% if @tasks.empty? %>
    <h4>It looks like you don't have any tasks. Why not create new one?</h4>
  <% else %>
    <div class="row">
      <% @tasks.each_with_index do |task, index| %>
        <%= render partial: "task", locals: {task: task, index: index } %>
      <%end %>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="default-block">
  <%= render partial: "messages/errors", locals: {resource: @task} %>
  <h2>New Task</h2>
  <div class="line-dark"></div>
    <%= form_for [@project, @task] do |f| %>
      <div class="form-group">
        <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
          <%= f.text_field :description, class: "form-control"%>
      </div>
      <div class="form-group">
        <%= f.label :due_date %>
          <%= f.date_select(:due_date, :order => [:month, :day, :year]) %>
      </div>
      <div class="form-group">
        <%= f.label :assigned_users, value: "Assign Users", class: "label-block" %>
          <%= f.collection_check_boxes(:assigned_user_ids, @task_users, :id, :name, html: {class: "form-control"})%>
      </div>
      <div class="form-group">
        <%= f.label :tag_names, "Tags (Comma seperated)" %>
          <%= f.text_field :tag_names, class: "form-control"%>
      </div>
      <div class="form-group">
        <%= f.hidden_field :project_id, value: @project.id %>
        <%= f.hidden_field :owner_id, value: @user.id %>
        <%= f.submit class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/overdue.html.erb
<%= render partial: "project_task_options", locals:{overdue: @overdue, active: @active, complete: @complete} %>
<div class="default-block">
  <h2>Overdue Tasks</h2>
  <div class="line-dark"></div>
  <% if @tasks.empty? %>
    <h4><%= "You don't have any late projects. Good job!" %></h4>
  <% else %>
    <div class="row">
      <% @tasks.each_with_index do |task, index| %>
        <%= render partial: "task", locals: {task: task, index: index } %>
      <%end %>
    </div>

  <% end %> <!-- if/else end -->

</div> <!-- block end -->

app/views/tasks/quick_new_task.html.erb
<div class="default-block">
  <%= render partial: "messages/errors", locals: {resource: @task} %>
  <h2>Quick Add Task</h2>
    <div class="line-dark"></div>
    <%= form_for(@task, {url: post_quick_new_task_path, controller: "tasks", action: "create", method: "post", html: {class: "form-inline"}}) do |f| %>
      <div class="form-group">
        <%= f.label :name, class: "label-block"%>
          <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description, class: "label-block" %>
          <%= f.text_field :description, class: "form-control"%>
      </div>
      <div class="form-group">
        <%= f.label :due_date, class: "label-block" %>
          <%= f.date_select(:due_date, :order => [:month, :day, :year]) %>
      </div>
      <div class="form-group">
        <%= f.label :tag_names, value: "Tags (Comma seperated)", class: "label-block" %>
          <%= f.text_field :tag_names, class: "form-control"%>
      </div>
      <div class="form-group project-select">
        <%= f.label :project_id, "Project", class: "label-block"  %>
          <%= collection_select(:task, :project_id, @projects, :id, :name, { include_blank: true }) %>
      </div>
      <div class="form-group">
        <%= f.hidden_field :owner_id, value: @user.id %>
        <%= f.submit class: "btn btn-primary"%>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="row">

  <div class="col-md-4">

    <div class="default-block">
      <h2><%= @task.name %></h2>
      <div class="line-dark"></div>
      <p> Created: <%= @task.friendly_created_at %> by <%= @task.owner.name %></p>
      <p> Due: <%= @task.due_date %> </p>
      <p> Status: <%= @task.status %></p>
      <p> Assigned to: <% @assigned_users.each do |user| %>
        <%= user.name %>,
          <% end %>
      </p>
      <p> Tags: <%@tags.each do |tag| %> 
          <%= tag.name %>,
          <% end %>
      </p>
      <p><%= @task.description %></p>
      <div class="inline-button">    
        <%= link_to "Edit Task", edit_task_path(@task), class: "btn btn-sm btn-primary" %>
      </div>
      <div class="inline-button">
        <%= render partial: "tasks/task_complete_form", locals: {task: @task} unless @task.complete? %>
      </div>
      <div class="inline-button">
        <%= button_to "Delete Task", task_path(@task), method: :delete, class: "btn btn-sm btn-danger" %>
        </div>
    </div> <!-- default block end  -->

    <div class="default-block">
      <%= render partial: "messages/errors", locals: {resource: @comment} %>
      <h3>New Comment</h3>
      <div class="line-dark"></div>
      <%= render partial: "comments/new_form", locals: {comment: @comment} %>
    </div> <!-- default block end  -->

  </div> <!-- col-md-4 end -->

  <div class="col-md-8">
    <div class="default-block">
      <h3>Comments</h3>
      <div class="line-dark"></div>
      <% @comments.each_with_index do |comment, index| %>
        <%= render partial: "comments/comment", locals: {comment: comment, index: index, col: ""} %>
      <%end %>
    </div> <!-- default block end  -->
  </div> <!-- col-md-8 end -->

</div> <!-- Row end -->