config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }, skip: [:sessions] 
    as :user do
      get 'login' => 'devise/sessions#new', :as => :new_user_session
      post 'login' => 'devise/sessions#create', :as => :user_session
      delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    end

  devise_scope :user do
    get "/signup" => "users/registrations#new"
    get "/profile" => 'users/registrations#edit'
  end

  resources :tags

  scope "/tasks" do
    get'/new', to: 'tasks#quick_new_task', as: "quick_new_task"
    post'/', to: 'tasks#create', as: "post_quick_new_task"
    get'/all-active-tasks', to: 'tasks#all_active_tasks', as: "all_active_tasks"
    get'/all-complete-tasks', to: 'tasks#all_complete_tasks', as: "all_complete_tasks"
    get'/all-overdue-tasks', to: 'tasks#all_overdue_tasks', as: "all_overdue_tasks"
  end

  resources :projects do
    get :overdue, on: :collection
    get :complete, on: :collection

    post '/delete_collaborator', to: 'projects#delete_collaborator'

    resources :comments, :notes, shallow: true

    resources :tasks, shallow: true do 
      get :complete, on: :collection, to: "tasks#complete"
      get :overdue, on: :collection, to: "tasks#overdue"
    end
  end

  patch '/edit_user_project_permission', to: 'user_projects#edit_user_project_permission'

  namespace :admin do 
    get 'dashboard' => 'dashboard#index', :as => :dashboard
    get 'tags' => 'dashboard#tags', :as => :tags
    get 'users' => 'dashboard#users', :as => :users
    get 'users/:id' => 'dashboard#user_edit', :as => :user_edit
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  include DateTimeConverter
  include IndexCheck
  
  has_many :notes

  has_many :tasks
  has_many :tags, through: :tasks
  has_many :comments, through: :tasks
  enum status: [:active, :complete]

  has_many :user_projects, foreign_key: "collaboration_project_id"
  has_many :collaborators, through: :user_projects
  belongs_to :owner, class_name: "User"

  scope :complete, -> { where(status: 1) }
  scope :active, -> { where(status: 0)}
  scope :overdue, -> { where("due_date < ? AND status = ?", Date.today, 0)}
  
  validates :name, :description, :due_date, :status, presence: true 

  def collaborator_emails=(emails)
    email_array = emails.split(",").map{|email| email.strip}
    email_array.each do |email|
      collaborator = User.find_by(email: email)
      if collaborator == nil || collaborator == self.owner || self.collaborators.include?(collaborator)
        next
      end
      self.collaborators << collaborator
      self.save
    end
  end

  def collaborator_emails
    emails = self.collaborators.collect {|collaborator| collaborator.email}
    emails.join(", ")
  end

  def notes_attributes=(attributes)
    attributes.each do |k,v|
      if v["title"].blank? && v["content"].blank?
        next
      else
        self.notes.build(v)
      end
    end
  end


  def active_tasks
    self.tasks.active 
  end

  def complete_tasks
    self.tasks.complete
  end

  def overdue_tasks
    self.tasks.overdue
  end

  def tasks_complete?
    tasks.any? { |task| task.status == "active"} ? false : true
  end

  def overdue?
    self.due_date < Date.today ? true : false
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout "projects_layout"
  before_action :set_project, except: [:create]
  before_action :project_statuses_count, only: [:index, :complete, :overdue]

  ## STANDARD RESTFUL ACTIONS

  def index
    @projects = (@user.active_projects + @user.collaboration_projects.active).reverse
  end

  def new
    @project = Project.new
    @project.notes.build
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_path(@project)
    else
      @project
      render :new
    end
  end

  def show
    authorize @project
    @project = Project.find_by(id: params[:id])
    @user_projects = UserProject.projects(@project.id)
  end

  def edit 
    authorize @project
    @project = Project.find_by(id: params[:id])
    @collaborators = @project.collaborators
    @user_projects = UserProject.projects(@project.id)
  end

  def update
    authorize @project
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      render :show
    end
  end

  def destroy
    authorize @project
    @project.destroy
    redirect_to projects_path
  end

  ## ADDITIONAL ACTIONS
  
  def delete_collaborator
    authorize @project
    user = User.find_by(id: params[:user][:id])
    @project.collaborators.delete(user)
    @project.save
    redirect_to project_path(@project)
  end

  def complete_tasks
    @tasks = @project.tasks.complete
  end

  def complete
    @projects = (@user.complete_projects + @user.collaboration_projects.complete).reverse
  end

  def overdue
    @projects = (@user.projects.overdue + @user.collaboration_projects.overdue).reverse
  end

  ## PRIVATE METHODS

  private
  def set_project
    if params[:id]
       @project = Project.find_by(id: params[:id])
    else
      @project = Project.find_by(id: params[:project_id])
    end
  end

  def project_statuses_count
    @overdue = (current_user.overdue_projects + current_user.collaboration_projects.overdue).uniq.count
    @active = (current_user.active_projects + current_user.collaboration_projects.active).uniq.count
    @complete = (current_user.complete_projects + current_user.collaboration_projects.complete).uniq.count
  end

  def project_params
    params.require(:project).permit(:name, :description, :collaborator_emails, :owner_id, :due_date, :status, notes_attributes: [:title, :content, :user_id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_add_collaborator_form.html.erb
<%= form_for(project) do |f| %>
  <div class="form-group">
    <%= f.label :collaborators, "Add users to collaborate by email, comma seperated" %>
      <%= f.text_field :collaborator_emails, value: nil, class: "form-control"%>
  </div>
  <div class="form-group">
  <%= f.hidden_field :project_id, value: project.id %>
  <%= f.hidden_field :owner_id, value: @user.id %>
  <%= f.submit "Add Users", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/projects/_delete_collaborator_form.html.erb
<%= form_for(person, url: project_delete_collaborator_path(@project), method: :post) do |f|%>
  <%= f.hidden_field :id %>
  <%= f.submit "Remove", class: "btn btn-xs btn-danger inline" %>
<% end %>

app/views/projects/_edit_collaborators_and_permissions_form.html.erb
<div class="row">
  <div class="col-xs-4">
    <p><%= user_project.collaborator.name %> (<%= user_project.permission %>)</p>
    <%= render partial: "delete_collaborator_form", locals: {person: user_project.collaborator} %>
  </div>

  <div class="col-xs-7">
    <%= form_for(user_project, url: edit_user_project_permission_path ) do |f| %>
    <div class="form-group inline">
      <%= f.label :permission, class: "label-block" %>
        <%= f.select :permission, UserProject.permissions.collect {|k,v| k}, selected: user_project.permission %>
    </div>
    <div class="form-group inline">
      <%= f.hidden_field :project_id, value: project.id %>
      <%= f.hidden_field :id, value: user_project.id %>
      <%= f.submit "Update Permission", class: "form-control btn-sm btn-primary" %>
    </div>
    <% end %>
  </div>
</div>
<div class="line-light"></div>

app/views/projects/_edit_form.html.erb
<%= form_for(project) do |f| %>
  <div class="form-group">
  <%= f.label :name, class: "control-label"%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :description, class: "control-label"%>
    <%= f.text_field :description,  class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :due_date, class: "control-label"%>
    <%= f.date_select :due_date, :order => [:month, :day, :year], class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :collaborators, "Add users to collaborate by email, comma seperated" %>
      <%= f.text_field :collaborator_emails, value: nil, class: "form-control"%>
  </div>
  <% if project.tasks_complete? %>
    <div class="form-group">
      <%= f.label :status, class: "label-block" %>
      <%= f.select :status, Project.statuses.collect {|k,v| [k.capitalize, k]}, selected: project.status %>
    </div>
  <% else %>
    <div class="form-group">
      <%= f.label :status, class: "label-block" %>
      <span class="incomplete"> You can mark a project complete after you've completed all tasks.</span>
    </div>
  <% end %>
  <div class="form-group">
  <%= f.hidden_field :project_id, value: project.id %>
  <%= f.hidden_field :owner_id, value: @user.id %>
  <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>
<%= link_to "Delete Project", project_path(project), method: :delete, class: "btn btn-danger"%>

app/views/projects/_new_form.html.erb
<%= form_for(project) do |f| %>
  <div class="form-group">
  <%= f.label :name, class: "control-label"%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :description, class: "control-label"%>
    <%= f.text_field :description,  class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :due_date, class: "control-label"%>
    <%= f.date_select :due_date, :order => [:month, :day, :year], class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :collaborators, "Collaborators (Email address, comma seperated)" %>
      <%= f.text_field :collaborator_emails, class: "form-control"%>
  </div>
  <div class="form-group">
  <%= f.label :notes, "Add a note", class: "control-label"%><br/>
    <%= f.fields_for :notes do |note_field| %>
    Title:
    <%= note_field.text_field :title, class: "form-control" %><br/>
    <%= note_field.text_area :content, rows: 3, class: "form-control" %>
    <%= note_field.hidden_field :user_id, value: @user.id %>
  <% end %>
  </div>
  <div class="form-group">
  <%= f.hidden_field :owner_id, value: @user.id %>
  <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="col-md-4">
  <h3> <%= link_to project.name, project_path(project) %> </h3>
  <span class="overdue"> <%= "Overdue" if project.overdue? && !project.complete?%></span>
  <% if project.owner == current_user %>
    <p class="owner-text"> You're an owner </p>
  <% else %>
    <p class="collaborator-text"> You're a collaborator</p>
  <% end %>
  <p> <%= project.description %> </p>
  <p> Created: <%= project.friendly_created_at %> </p>
  <p> Due: <%= project.due_date %> </p>
  <p> Status: <%= project.status.capitalize %> </p>
  <p> Collaborators: <% project.collaborators.each do |person| %> <%= person.name %> <%end%> </p>
  <p> <%= link_to "#{project.comments.count} Comments", project_comments_path(project)%> </p>
  <div class="inline-button">
    <%= link_to "View Project", project_path(project), class: "btn btn-default" %>
  </div>
  <div class="inline-button">
    <%= link_to "Edit Project", edit_project_path(project), class: "btn btn-default" %>
  </div>
  <div class="inline-button">
    <%= link_to "View Tasks", project_tasks_path(project), class: "btn btn-default" %>
  </div>
 <div class="line-light"> </div>
</div>
<% if project.index_check(index) %>
  <div class="clearfix"></div>
<% end %>

app/views/projects/_projects_status_filter.html.erb
<div class="default-block">
  <div class="inline-button">
    <%= link_to "Active Projects ( #{active} )", projects_path, class: "btn btn-warning" %> 
  </div>
  <div class="inline-button">
    <%= link_to "Complete Projects ( #{complete} )", complete_projects_path, class: "btn btn-success" %>
  </div>
  <div class="inline-button">
    <%= link_to "Overdue Projects ( #{overdue} )", overdue_projects_path, class: "btn btn-danger" %>
  </div>
</div>

app/views/projects/_quick_add_form.html.erb
<%= form_for(project, html: {class: "form-inline"}) do |f| %>
  <div class="form-group quick-add-form-group">
    <%= f.label :name, class: "control-label"%>
      <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "control-label"%>
      <%= f.text_field :description,  class: "form-control quick-add-form-group" %>
  </div>
  <div class="form-group">
    <%= f.label :due_date, class: "control-label"%>
      <%= f.date_select :due_date, order: [:month, :day, :year], class: "date-select quick-add-form-group"%>
  </div>
  <div class="form-group">
    <%= f.hidden_field :owner_id, value: @user.id %>
    <%= f.submit class: "btn btn-primary quick-add-form-group"%>
  </div>
<% end %>

app/views/projects/complete.html.erb
<%= render partial: "projects_status_filter", locals:{overdue: @overdue, active: @active, complete: @complete} %>

<div class="default-block">
  <h2>Complete Projects</h2>
  <div class="line-dark"></div>
  <% if @projects.empty? %>
    <h4><%= "You haven't completed any projects yet." %></h4>
  <% else %>
    <div class="row">
      <% @projects.each_with_index do |project, index| %>
        <%= render partial: "project", locals: {project: project, index: index} %>
      <%end %>
    </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<div class="row">
    <div class="col-md-6">
      <div class="default-block">
      <h2>Edit Project</h2>
      <div class="line-dark"></div>
      <%= render partial: "messages/errors", locals: {resource: @project} %>
      <%= render partial: "edit_form", locals: {project: @project} %>
    </div>
    </div>
    <div class="col-md-6"> 
      <div class="default-block">
        <h3>Edit Collaborators</h3>
        <div class="line-dark"></div>
        <% @user_projects.each do |user_project, index| %>
          <%= render partial: "edit_collaborators_and_permissions_form", locals: {user_project: user_project, project: @project, index: index} %>
        <%end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<%= render partial: "projects_status_filter", locals:{overdue: @overdue, active: @active, complete: @complete} %>

<div class="default-block">
  <h2>Active Projects</h2>
  <div class="line-dark"> </div>
  <% if @projects.empty? %>
    <h4><%= "You don't have any projects yet. Why not start by creating a new one?" %></h4>
  <% else %>
    <div class="row">
      <% @projects.each_with_index do |project, index| %>
        <%= render partial: "project", locals: {project: project, index: index} %>
      <%end %>
    </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="default-block">
  <%= render partial: "messages/errors", locals: {resource: @project} %>
  <%= render partial: "new_form", locals: {project: @project, task: @task} %>
</div>

app/views/projects/overdue.erb
<%= render partial: "projects_status_filter", locals:{overdue: @overdue, active: @active, complete: @complete} %>

<div class="default-block">
  <h2>Overdue Projects</h2>
  <div class="line-dark"></div>
  <% if @projects.empty? %>
    <h4><%= "You don't have any late projects. Good job!" %></h4>
  <% else %>
    <div class="row">
      <% @projects.each_with_index do |project, index| %>
        <%= render partial: "project", locals: {project: project, index: index} %>
      <%end %>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="default-block">
  <h2> <%= @project.name %> <%= "✓" if @project.complete? %> <span class="overdue"> <%= "Overdue" if @project.overdue? && !@project.complete? %></span> </h2>
  <div class="line-dark"></div>
  <div class="inline-button">
    <%= link_to "Edit Project", edit_project_path(@project), class: "btn btn-primary" %>
  </div>
  <div class="inline-button">
    <%= link_to "New Task", new_project_task_path(@project), class: "btn btn-primary" %>
  </div>
  <div class="inline-button">
    <%= link_to "View Comments", project_comments_path(@project), class: "btn btn-default" %>
  </div>
  <div class="inline-button">
    <%= link_to "View Notes", project_notes_path(@project), class: "btn btn-default" %>
  </div>
</div>

<div class="row">

  <div class="col-sm-4">
    <div class="default-block">
      <h3> Task Details </h3>
      <div class="line-dark"></div>
      <div class="inline-button"> 
        <%= link_to "#{@project.tasks.active.count} Open Tasks", project_tasks_path(@project), class: "btn btn-warning" %>
      </div>
      <div class="inline-button"> 
        <%= link_to "#{@project.tasks.complete.count} Complete Tasks", complete_project_tasks_path(@project), class: "btn btn-success" %>
      </div>
      <div class="inline-button"> 
        <%= link_to "#{@project.tasks.overdue.count} Overdue Tasks", overdue_project_tasks_path(@project), class: "btn btn-danger" %>
      </div>
      <div class="line-light"></div>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="default-block">
      <h3> Project Details </h3>
      <div class="line-dark"></div>
      <span class="overdue"> <%= "Overdue" if @project.overdue? && !@project.complete? %></span>
      <p> <%= @project.description %> </p>
      <p> Created: <%= @project.friendly_created_at %> </p>
      <p> Due: <%= @project.due_date %> </p>
      <p> Status: <%= @project.status %> </p>
      <div class="inline-button">
      <%= link_to "#{@project.comments.count} Comments", project_comments_path(@project), class: "btn btn-default" %>
      </div>
      <div class="inline-button">
        <%= link_to "#{@project.notes.count} Notes", project_notes_path(@project), class: "btn btn-default" %>
      </div>
      <div class="line-light"></div>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="default-block">
      <h3> People </h3>
      <div class="line-dark"></div>
      <p> <%= @project.owner.name %> (Owner) </p>
      <% @user_projects.each do |up| %>
        <div class="row">
          <div class="col-xs-12">
            <div class="inline"> <p> <%= up.collaborator.name  %> (<%= up.permission  %>)</p> </div>
            <div class="inline"> <%= render partial: "delete_collaborator_form", locals: {person: up.collaborator} %> </div>
          </div>
        </div>
      <% end %>
        <%= render partial: "add_collaborator_form", locals: {project: @project} %>
      <div class="line-light"></div>
    </div>
  </div>

</div> <!-- end row -->