config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }, skip: [:sessions] 
    as :user do
      get 'login' => 'devise/sessions#new', :as => :new_user_session
      post 'login' => 'devise/sessions#create', :as => :user_session
      delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    end

  devise_scope :user do
    get "/signup" => "users/registrations#new"
    get "/profile" => 'users/registrations#edit'
  end

  resources :tags

  scope "/tasks" do
    get'/new', to: 'tasks#quick_new_task', as: "quick_new_task"
    post'/', to: 'tasks#create', as: "post_quick_new_task"
    get'/all-active-tasks', to: 'tasks#all_active_tasks', as: "all_active_tasks"
    get'/all-complete-tasks', to: 'tasks#all_complete_tasks', as: "all_complete_tasks"
    get'/all-overdue-tasks', to: 'tasks#all_overdue_tasks', as: "all_overdue_tasks"
  end

  resources :projects do
    get :overdue, on: :collection
    get :complete, on: :collection

    post '/delete_collaborator', to: 'projects#delete_collaborator'

    resources :comments, :notes, shallow: true

    resources :tasks, shallow: true do 
      get :complete, on: :collection, to: "tasks#complete"
      get :overdue, on: :collection, to: "tasks#overdue"
    end
  end

  patch '/edit_user_project_permission', to: 'user_projects#edit_user_project_permission'

  namespace :admin do 
    get 'dashboard' => 'dashboard#index', :as => :dashboard
    get 'tags' => 'dashboard#tags', :as => :tags
    get 'users' => 'dashboard#users', :as => :users
    get 'users/:id' => 'dashboard#user_edit', :as => :user_edit
  end

end

app/views/navs/_nav_base.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <!-- Brand and mobile toggle -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Rails PM", root_path, class: "navbar-brand" %>
    </div>

    <!-- Nav links -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user && user_signed_in? %>
          <%= render "navs/nav_logged_in" %>
        <% else %>
          <%= render "navs/nav_logged_out" %>
        <% end %>
      <ul>
    </div>

  </div><!-- end container-fluid -->
</nav>

app/views/navs/_nav_logged_in.html.erb
<% if current_user.admin? %>
  <li><%= link_to "Admin", admin_dashboard_path %></li>
<% end %>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><%= link_to "New Project", new_project_path %></li>
    <li><%= link_to "Your Projects", projects_path %></li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tasks <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><%= link_to "New Task", quick_new_task_path %></li>
    <li><%= link_to "Your Tasks", all_active_tasks_path %></li>
  </ul>
</li>
<li><%= link_to "Tags", tags_path %></li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><%= link_to "Profile", profile_path %></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
  </ul>
</li>
<li><%=link_to "Logged in as: #{current_user.email}", profile_path %></li>

app/views/navs/_nav_logged_out.html.erb
<li><%= link_to "Sign Up", signup_path %></li>
<li><%= link_to "Login", new_user_session_path %></li>

app/views/navs/_projects_sub_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
      <ul class="subnav nav navbar-nav">
        <li><%= link_to "View Project", project_path(@project) %></li>
        <li><%= link_to "Tasks", project_tasks_path(@project) %></li>
        <li><%= link_to "Notes", project_notes_path(@project) %></li>
        <li><%= link_to "Comments", project_comments_path(@project) %></li>
      <ul>
  </div>
</nav>